### ISSUE TITLE
Travis failing on both master and devel branch

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#371]
This is the error: 
~~~
119/120 Test #119: PythonGeometryTests .......................................***Failed    0.14 sec

Traceback (most recent call last):

  File "geometry.py", line 16, in <module>

    import iDynTree

  File "/usr/local/lib/python2.7/dist-packages/iDynTree.py", line 28, in <module>

    _iDynTree = swig_import_helper()

  File "/usr/local/lib/python2.7/dist-packages/iDynTree.py", line 24, in swig_import_helper

    _mod = imp.load_module('_iDynTree', fp, pathname, description)

ImportError: libidyntree-modelio-symoro.so: cannot open shared object file: No such file or directory
~~~

I suspect it is related to the latest Travis update: 
* https://blog.travis-ci.com/2017-08-29-trusty-image-updates
* https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/
* https://github.com/travis-ci/travis-ci/issues/8315

**Comment by traversaro** [comment]
We don't use anymore Travis and we now have running CI test for Python bindings, so I think we can close the issue.
